apiVersion: v1
kind: Application
name: New Application
config:
  port: 8080
entities:
  User: 
    table: APP_USERS
    columns:
      id: PK, Long, Unique
      uuid: UUID
      organizationId: Long
      userName: String, Min=5, Max=100
  Role:
    table: APP_ROLES
    columns:
      id: PK, Long, Unique
      uuid: UUID
      organizationId: Long
  UserRole:
    table: APP_USER_ROLES
    columns:
        user: Entity=User, OneToMany
        role: Entity=Role, ManyToOne
        status: Enum=Status
enums:
  Status: 
    values: Active, Passive, Deleted